### PR TITLE
Performance improvement by using NSRange

### PR DESCRIPTION
**Pull request by simonbs**
When pasting large blocks of text into the SyntaxTextView, the main thread would be blocked for a relatively large amount of time. I found that this happens because distance(from:to) on a Swift string is very slow. SyntaxTextView would call this in colorTextView(lexerForSource:) when the text changed to convert a Swift Range to an NSRange.

This can be avoided by returning an NSRange rather than a Range\<Int\> when conforming to the Token protocol. I realize that this doesn't feel natural in Swift but I think the performance improvement outweighs the advantages that the current interface has. Besied, it's likely to be trivial for whoever conforms to the Token protocol to create an NSRange.

I've attached screenshots of two very non-scientific measurements I made in with the Time Profiler in Instruments. The first uses Range\<Int\> and the second uses NSRange.

screen shot 2018-05-06 at 19 52 42
screen shot 2018-05-06 at 19 52 35

### CODE REVIEW

**Comment by louisdh** [comment]
Thanks for suggestion. 

The current `Range<Int>` specifies indices in UTF8. I wonder if the `Range<Int>` could stay, by expecting the range in UTF16 instead, and adding documentation that says it's in UTF16. That way SavannaKit's public API doesn't rely on `NSRange`, and the performance issue is solved. Then the `Token` protocol would get an internal extension that creates an `NSRange` from the `Range<Int>`. To prevent any confusion, we could also rename the `range` property to `utf16Range`.

**Comment by louisdh** [comment]
Another approach might be to create a `UTF8Token` and `UTF16Token`. And let SavannaKit convert the `UTF8Token` as it does with the current `Token` implementation. `UTF16Token` would of course be fastest.

**Comment by louisdh** [comment]
Been thinking about this, and perhaps this is the best solution:

```
public enum TokenEncoding {
    case utf8
    case utf16
}

public protocol Token {

    var savannaTokenType: TokenType { get }

    var range: Range<Int>? { get }

    var encoding: TokenEncoding { get }

}
```

So when the user provides tokens with a `utf16` encoding, we can convert this to an NSRange without much trouble. When the encoding is `utf8`, we need to do the conversion as it’s currently implemented. 

By making the encoding a requirement in the Token protocol, users are forced to think about what encoding they’re using with their tokens. Which hopefully prevents common mistakes. Btw: the enum and protocols should probably get some documentation with more details about which encoding is appropriate. But I’d consider that another issue, so don’t worry too much about that for now.

**Comment by simonbs** [comment]
Thanks for your feedback.

In my eager to improve the performance when inserting large blocks of texts, I overlooked the importance of the encoding. I'll take a look at your feedback and see if I can come up with an implementation. I guess another thing to remember when implementing this is to ensure support for emojis 😃

**Comment by louisdh** [comment]
Actually, the part about "When the encoding is utf8, we need to do the conversion as it’s currently implemented." that I described might be wrong. Swift's String.count doesn't return the length in UTF8, rather it returns it in "swiftCharacters". But the idea of having a TokenEncoding enum still stands, it's just the naming of the utf8 case that should be different. 

Edit: Apparently the correct terminology for a Swift character is "extended grapheme cluster".

**Comment by simonbs** [comment]
I've been testing out a few things and I've found that when a UTF16 encoded token returns `Range<String.Index>` rather than `Range<Int>` the performance is much improved even when doing the conversion to NSRange later. Using `Range<String.Index>` might even make sense since we are in fact dealing with indices in a string.

Would it be a solution to simply return `Range<String.Index>` and keep the conversion and keep to UTF16 and NSRange in SavannaKit?

**Comment by louisdh** [comment]
You’re absolutely right, `Range<String.Index>` makes a lot of sense for defining the range of a token in Swift. Good to hear that there’s no real performance issue with it.

**Comment by simonbs** [comment]
I'm closing this in favour of #9.

**Pull request closed without merging**
